name: Streamlit Smoke Test

on:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ci.txt
      - name: Launch Streamlit (background) and curl health
        run: |
          nohup python -m streamlit run app.py --server.port=8501 --server.headless=true &
          sleep 5
          curl -sSf http://localhost:8501 || (echo "Streamlit did not start" && exit 1)
